# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=255),
        ),
    ]
