# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20160806_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Category')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Movie')),
            ],
        ),
    ]
